import Head from "next/head";
import styled from "styled-components";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>Welcome to mypage</Container>
    </>
  );
}

const Container = styled.div`
  font-size: 80px;
  font-family: "InkLipquid";
  font-weight: 100;
`;
